### ISSUE TITLE
Not found textobj#blockwise#region_from_textobj

### ISSUE THREAD

**Issue by kyouryuukunn** [osyo-manga/vim-operator-blockwise#1]
お久しぶりです｡
久しぶりに使用したところ以下のようにtextobj#blockwise#region_from_textobj()が見つからないとｴﾗｰが出ました｡

function operator#blockwise#operator[6]..<SNR>137_operator_blockwise[4]..<SNR>137_blockwise_yank[6]..<SNR>137_blockwise[5]..<SNR>137_region の処理中にｴﾗｰが検出されました:
行 1:
E117: 未知の関数です: textobj#blockwise#region_from_textobj
E116: 関数の無効な引数です: get(textobj#blockwise#region_from_textobj(a:textobj), 1, [])
E15: 無効な式です: get(textobj#blockwise#region_from_textobj(a:textobj), 1, [])

**Comment by osyo-manga** [comment]
ありがとうございます！
とりあえず、[textobj-blockwise](https://github.com/osyo-manga/vim-textobj-blockwise) を入れてもらえると動作すると思います。
ただ、依存してしまうのはいまいちなので、依存しないように変更しようとは思っています。

**Comment by kyouryuukunn** [comment]
ありがとうございます。動作確認できました。
